apps:
  pages:
    - number: 1
      items:
        - App Store
        - Books
        - Bitcoin Core
        - Brave Browser
        - Contacts
        - Docker
        - iTerm
        - Maps
        - Messages
        - Photos
        - Postman
        - Reminders
        - Roam Research
        - Safari
        - Sequel Pro
        - Signal
        - Slack
        - Spotify
        - System Preferences
        - Transmission
        - TV
        - zoom.us
        - folder: Utilities
          pages:
            - number: 1
              items:
                - Calculator
                - Digital Color Meter
                - Disk Utility
                - Font Book
                - Grapher
                - Mission Control
                - ProtonVPN
                - Rectangle
                - Siri
        - folder: Video
          pages:
            - number: 1
              items:
                - QuickTime Player
                - iMovie
                - OBS
                - mpv
                - VLC
        - folder: Productivity
          pages:
            - number: 1
              items:
                - Calendar
                - Google Chrome
                - Dictionary
                - FaceTime
                - Mail
                - Music
                - Notes
                - Numbers
                - Preview
                - Stickies
                - TextEdit
        - folder: Entertainment
          pages:
            - number: 1
              items:
                - Chess
                - Photo Booth
        - folder: Misc
          pages:
            - number: 1
              items:
                - Chromebook Recovery Utility
                - Find My
                - Home
                - News
                - Podcasts
                - Stocks
                - Shortcuts
                - Voice Memos
        - folder: Other
          pages:
            - number: 1
              items:
                - AirPort Utility
                - Automator
                - Bluetooth File Exchange
                - ColorSync Utility
                - Time Machine
                - Image Capture
                - VoiceOver Utility
                - Migration Assistant
                - Terminal
                - Activity Monitor
                - Console
                - Keychain Access
                - System Information
                - Script Editor
                - Boot Camp Assistant
                - Screenshot
                - Audio MIDI Setup
widgets:
  pages: []
dock_items:
  settings:
    autohide: true
    largesize: 128
    magnification: false
    minimize-to-application: true
    mru-spaces: false
    show-recents: false
    tilesize: 48
desktop: {}
