apps:
  pages:
    - number: 1
      items:
        - App Store
        - Bitcoin Core
        - Books
        - Brave Browser
        - Contacts
        - Docker
        - iMovie
        - iTerm
        - Maps
        - Messages
        - mpv
        - OBS
        - Photos
        - Postman
        - ProtonVPN
        - Reminders
        - Safari
        - Sequel Pro
        - Signal
        - Slack
        - Spotify
        - System Preferences
        - System Settings
        - Transmission
        - TV
        - Weather
        - zoom.us
        - folder: Entertainment
          pages:
            - number: 1
              items:
                - Chess
                - Photo Booth
        - folder: Apple
          pages:
            - number: 1
              items:
                - Calendar
                - Clock
                - Dictionary
                - FaceTime
                - Freeform
                - Home
                - Mail
                - Music
                - News
                - Notes
                - Podcasts
                - QuickTime Player
                - Stickies
                - Stocks
                - TextEdit
                - Voice Memos
        - folder: Other
          pages:
            - number: 1
              items:
                - Activity Monitor
                - AirPort Utility
                - Automator
                - Audio MIDI Setup
                - Bluetooth File Exchange
                - Boot Camp Assistant
                - ColorSync Utility
                - Console
                - Grapher
                - Image Capture
                - Migration Assistant
                - Mission Control
                - Screenshot
                - Script Editor
                - System Information
                - Terminal
                - Time Machine
                - VoiceOver Utility
        - folder: Utilities
          pages:
            - number: 1
              items:
                - Calculator
                - Digital Color Meter
                - Disk Utility
                - Find My
                - Font Book
                - GPG Keychain
                - Keychain Access
                - Preview
                - Print Center
                - Rectangle
                - Screen Sharing
                - Shortcuts
                - Siri
widgets:
  pages: []
dock_items:
  settings:
    autohide: true
    largesize: 128
    magnification: false
    minimize-to-application: true
    mru-spaces: false
    show-recents: false
    tilesize: 48
desktop: {}
