# Install system utilities
install_or_upgrade_package git
install_or_upgrade_package gpg
install_or_upgrade_package openssl
install_or_upgrade_package mobile-shell

# Install fun software
install_or_upgrade_package irssi

# Install dev tools
install_or_upgrade_package android-platform-tools
install_or_upgrade_package awscli
install_or_upgrade_package aws-elasticbeanstalk
install_or_upgrade_package docker-machine
install_or_upgrade_package nvm
install_or_upgrade_package python3
