# Install system utilities
install_or_upgrade_package brew-cask
install_or_upgrade_package git
install_or_upgrade_package gpg
install_or_upgrade_package openssl

# Install fun software
install_or_upgrade_package irssi

# Install dev tools
install_or_upgrade_package android-platform-tools
install_or_upgrade_package ansible
install_or_upgrade_package awscli
install_or_upgrade_package aws-elasticbeanstalk
install_or_upgrade_package boot2docker
install_or_upgrade_package docker
install_or_upgrade_package node
install_or_upgrade_package python3
