tap "caskroom/fonts"
tap "buo/cask-upgrade"
brew "asdf"
brew "bash"
brew "bash-completion"
brew "docker-compose"
brew "git"
brew "pinentry-mac"
brew "mobile-shell"
brew "neovim"
brew "openssl"
brew "pyenv"
brew "rg"
brew "watchman"
brew "yarn", args: ["--without-node"]
cask "bitcoin-core"
cask "firefox-developer-edition"
cask "google-chrome"
cask "gpg-suite-no-mail"
cask "imageoptim"
cask "iterm2"
cask "postman"
cask "protonvpn"
cask "psequel"
cask "qlcolorcode"
cask "qlstephen"
cask "qlmarkdown"
cask "quicklook-json"
cask "resilio-sync"
cask "sequel-pro"
cask "signal"
cask "spectacle"
cask "spotify"
cask "tor-browser"
cask "transmission"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-twitter-color-emoji"
cask "vlc"
mas "Slack", id: 803453959
mas "Next Meeting", id:1017470484
mas "Giphy Capture", id:668208984