---
- hosts: localhost
  connection: local
  user: $USER

  vars_files:
    - vars.yml

  tasks:
    - name: "Installing nvm"
      shell: |
        touch ~/.bash_profile
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: "Installing NodeJS version {{ node_default_version }}"
      shell: |
        source $HOME/.nvm/nvm.sh
        nvm install {{ node_default_version }}
      args:
        executable: /bin/bash

    - name: "Set default Node to version {{ node_default_version }}"
      shell: |
        source $HOME/.nvm/nvm.sh
        nvm alias default {{ node_default_version }}
      args:
        executable: /bin/bash
