---
- hosts: localhost
  connection: local
  user: $USER

  vars_files:
    - vars.yml

  # collect required information from the user
  vars_prompt:
    - name: ssh_public_key
      prompt: ssh public key

    - name: ssh_private_key
      prompt: ssh private key

    - name: ssh_key_passphrase
      prompt: ssh key passphrase
      private: yes
      confirm: yes

  tasks:
    - name: Creating SSH keys
      shell: |
        echo '{{ ssh_public_key }}' > $HOME/.ssh/id_rsa.pub
        echo '{{ ssh_private_key }}' > $HOME/.ssh/id_rsa

    - name: Change permission on SSH keys
      file:
        path: $HOME/.ssh/id_rsa.pub
        mode: '0644'
      file:
        path: $HOME/.ssh/id_rsa.pub
        mode: '0600'

    - name: Add SSH key to macOS keychain
      shell: |
        expect <<EOD
        spawn ssh-add -K $HOME/.ssh/id_rsa
        expect {
        "Enter passphrase for" {send "{{ ssh_key_passphrase }}\r"; exp_continue}
        }
        EOD
